version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: hr-postgres-simple
    restart: unless-stopped
    environment:
      POSTGRES_DB: hr_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Reem1994$
    ports:
      - "5433:5432"
    volumes:
      - postgres_simple_data:/var/lib/postgresql/data
    networks:
      - hr-simple-network

  # NestJS Application (Simple)
  app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: hr-app-simple
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:Reem1994$@postgres:5432/hr_management?schema=public
      JWT_SECRET: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc2MzU0MTA5OCwiZXhwIjoxNzYzNTQ0Njk4fQ._-V0hUKoz-4noPRIqNSjUy3cKqMkz-Lgms1SE1hDdY4
      JWT_EXPIRES_IN: "7d"
      PORT: 3000
      # Email configuration
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: reemhasan088@gmail.com
      SMTP_PASS: sisw pphu qhwo kabq
      SMTP_FROM: HR
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads
    networks:
      - hr-simple-network

volumes:
  postgres_simple_data:
    driver: local

networks:
  hr-simple-network:
    driver: bridge
